name=D6F-W04A1
version=0.1.0
author=Juarendra Ramadhani <jrjuarendra@gmail.com>
maintainer=Juarendra Ramadhani <jrjuarendra@gmail.com>
sentence=Robust non-blocking Arduino library for the Omron D6F-W04A1 MEMS air flow sensor.
paragraph=Robust non-blocking Arduino library for the Omron D6F-W04A1 MEMS air flow sensor. Includes major enterprise features and bug fixes.
category=Sensors
url=https://github.com/juarendra/D6F-W04A1-Arduino
architectures=*
includes=D6FW04A1.h
